FROM apache/airflow:2.9.3

USER root

# -------- SYSTEM DEPENDENCIES --------
RUN apt-get update && apt-get install -y \
    default-jdk \
    curl \
    vim \
    && apt-get clean

# -------- ENV VARIABLES (IMPORTANT FOR SPARK) --------
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH=$JAVA_HOME/bin:$PATH

# -------- SWITCH USER --------
USER airflow

# -------- PYTHON DEPENDENCIES --------
RUN pip install --no-cache-dir \
    pyspark \
    delta-spark \
    pandas

# -------- (OPTIONAL BUT GOOD) --------
# Avoid Spark hostname issues
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3


RUN pip install delta-spark==3.1.0
ENV PYSPARK_SUBMIT_ARGS="--packages io.delta:delta-core_2.12:2.4.0 pyspark-shell"